ci: minor version bump to v0.10.0 [skip ci]
Changes:

* test: fix error TS7006: Parameter 'onFulfilled' implicitly has an 'any' type., by @teamco
* chore: update deps, by @teamco
* Merge remote-tracking branch 'origin/main'
* feat(supabase): extract standardized supabase api into workspace package, by @teamco